### ISSUE TITLE
Milestone / Plan

### ISSUE THREAD

**Issue by MasatoDev** [MasatoDev/boostest#5]
- [x] Commonize test data creation logic, etc.
- [x] Add test for correct function creation (ts/js)
- [x] add error handlings to crates boostest
- [ ] Allow class properties to be overridden in functions that get instances of the class being created
- [x] Overall refactoring
- [ ] ...

**Comment by MasatoDev** [comment]
snapshot test were added!!💪

https://github.com/MasatoDev/boostest/pull/9

**Comment by MasatoDev** [comment]
done error handling! https://github.com/MasatoDev/boostest/pull/18

**Comment by MasatoDev** [comment]
add projectc for releasing ver 1.0.0.

https://github.com/users/MasatoDev/projects/4

**Comment by MasatoDev** [comment]
merge to ver1 specification.

https://github.com/MasatoDev/boostest/issues/31
